#!/bin/bash

function count()
{
if [ "$PROP__u" != "" ] && [ "$PROP__p" != "" ] && [ "$PROP__H" != "" ] && [ "$PROP__P" != "" ];
then
  echo "Authorisation completed."
  echo "Welcome $PROP__u."
else
  echo "Sorry, connection invalid. Please enter all the valid log-in details"
fi
}

##To apply on all blocks. 
